version: '3.8'

services:

  nginx:
    restart: "on-failure"
    ports:
      - "8080:80"
      - "8443:443"

  front:
    restart: "on-failure"
    environment:
      BUILD_TYPE: "Production" 

  back:
    restart: "on-failure"
    environment:
      BUILD_TYPE: "Production" 

  db:
    restart: "on-failure"
